---
extends: default
ignore: |
  **/megalinter-reports/**/*
  test/dummy/**/*
rules:
  comments-indentation:
    ignore: |
      *mega-linter.yml
  comments:
    ignore: |
      *mega-linter.yml
  line-length:
    ignore: |
      *mega-linter.yml
